### ISSUE TITLE
Error in consecutive days constraint?

### ISSUE THREAD

**Issue by hkgrov** [ekallevik/flexible_employee_scheduling#31]
I believe there is an error in how we handle consecutive days. If I understand the constraint correctly, we are checking L_C_D days ahead. L_C_D corresponds to the maximum number of consecutive days and employee should work. We are then subtracting L_C_D from this number. If an employee works all days we check ahead, then the maximum number we get is 0. The q_con-variable will therefore never be 1 and the constraint is redundant.

**Comment by ekallevik** [comment]
You are correct! The constraint won´t work as it is now. Fix is implemented and ready for review.

**Comment by hkgrov** [comment]
Issue seem to be fixed
