### ISSUE TITLE
get_durations()

### ISSUE THREAD

**Issue by sondrenaerland** [ekallevik/flexible_employee_scheduling#37]
get_durations() currently returns both the durations 21.75: [9.0] and 24.00: [6.75], corresponding to the demand periods 21:45 - 24:00 and 00:00 - 06:45. Unsure if we actually want to generate the duration 24:00: [6.75] in this case.

**Comment by sondrenaerland** [comment]
There is also issues like at day 58. Durations from 14:30 to 21:45 and 24:00 are created, even though there only exists demand from 14:30 to 16:30.

**Comment by sondrenaerland** [comment]
These problems are fixed in the updated shift design code from dev/sondre, I will create a pull request on this later.

**Comment by ekallevik** [comment]
How is this coming along @sondrenaerland ?

**Comment by sondrenaerland** [comment]
This is what I hope to fix today, but that probably won't be fixed completely before tomorrow. In the updated algorithm for design of shifts, I introduce a function creating periods of continuous and discontinuous demand (this is not self-explanatory), and this function will (after some modifications) replace the get_durations(). This would also solve the issue #38

**Comment by sondrenaerland** [comment]
Fixed in newest update.
